// CC-CMD-2026-08-09-token-resolution-audit.
//
// Closes the ceiling on CC-CMD-2026-08-09-phantom-css-token-audit's remaining
// ~46 text-colour declarations. It does NOT do so by screenshotting 46
// elements, because that was the wrong bar. Two reframes drive this file:
//
// REFRAME 1 -- verify the universal, not the instances.
//   A phantom token is structurally detectable at runtime: a var(--x) whose
//   --x resolves to empty on :root. So instead of asking "are these 46 right",
//   sweep the ENTIRE deployed CSSOM and prove ZERO unresolvable references
//   remain anywhere. That covers rules I never listed and never touched, and
//   it keeps covering them. Proof of absence beats 46 proofs of presence.
//
// REFRAME 2 -- most of the 46 are provably invisible, and no image could ever
// show otherwise.
//   The failure mode was: declaration invalid -> dropped -> element INHERITS.
//   body sets color:var(--white), and 41 of the ~50 fixes target --white. So
//   for any element not overridden between it and body, the fix turned
//   "inherits --white" into "explicitly --white": identical pixels. The honest
//   question is not "what does it look like" but "was this change observable
//   at all", and that is answerable without the old build -- inheritance IS
//   the old behaviour, still measurable in the current DOM. Compare each
//   element's computed colour with its parent's:
//     equal    -> provably invisible; cannot be a regression; needs no image
//     differs  -> the declaration is doing real work; a genuine visual delta
//
// Target selectors come from outbox/touched-selectors.json, generated by
// scripts/derive-touched-selectors.mjs from the fix commits themselves. Never
// hand-listed: a remembered list only checks what the author recalled, and the
// forgotten selector is the one that breaks.

const { chromium } = require('@playwright/test');
const fs = require('fs');

const URL = process.env.FIELD_URL || 'https://jubilant-bassoon.jeffunglesbee.workers.dev';
const TS = new Date().toISOString().replace(/[:.]/g, '-');
const VIEWPORT = { width: 1440, height: 900 };

const TOUCHED = JSON.parse(fs.readFileSync('outbox/touched-selectors.json', 'utf8'));

// The tokens CC-CMD-2026-08-09-phantom-css-token-audit DELIBERATELY left
// unresolved, each with a stated reason in
// outbox/cc-session-2026-08-09-phantom-css-token-audit.md: no reserved Rule 37
// meaning exists for green/orange/"accent", and red is reserved for
// "elimination urgency ONLY" so .vibe.blood cannot take it.
//
// Encoding them here is what makes L1 a usable gate rather than a permanent
// red light. Without it `conclusive` could never be true and the artifact
// would be ignored within a week. With it, any NEW unresolvable token fails
// loudly -- which is the regression this sweep exists to catch.
const STOP_LISTED = ['--green', '--red', '--orange', '--accent'];

(async () => {
  const browser = await chromium.launch(
    process.env.PW_EXECUTABLE ? { executablePath: process.env.PW_EXECUTABLE } : {});
  const page = await browser.newPage({ viewport: VIEWPORT });
  await page.goto(URL, { waitUntil: 'domcontentloaded', timeout: 20000 });
  await page.waitForSelector('.game-card', { timeout: 25000 }).catch(() => {});

  const result = await page.evaluate((touched) => {
    const rootCS = getComputedStyle(document.documentElement);
    const resolves = (name) => rootCS.getPropertyValue(name).trim() !== '';

    // ── L1: sweep every rule in every stylesheet ────────────────────────────
    const l1 = { rulesScanned: 0, sheetsScanned: 0, sheetsBlocked: 0,
                 unresolvedNoFallback: [], unresolvedWithFallback: [] };
    // `if (rule.cssRules) ... continue` would be WRONG, and was: modern
    // Chromium gives every CSSStyleRule a .cssRules list (empty) because CSS
    // nesting is supported, so that branch recursed into nothing and skipped
    // all 1539 style rules. The probe reported L1 PASS having scanned 51.
    // A style rule must be SCANNED and THEN recursed into, and the recursion
    // guard must test .length, not existence.
    const walk = (rules) => {
      for (const rule of rules) {
        if (rule.cssRules && rule.cssRules.length) walk(rule.cssRules);
        if (!rule.style) continue;
        l1.rulesScanned++;
        // style.cssText, NOT an index walk over rule.style. Iterating
        // properties enumerates LONGHANDS, and a shorthand carrying an
        // unresolvable var() (`border-color:var(--red)`) cannot be expanded at
        // parse time, so it is invisible to the index walk. The first run
        // found 8 fatal references where the stop-list says 13 -- the missing
        // ones were all shorthands. cssText is the rule as parsed and cannot
        // lose them.
        for (const decl of rule.style.cssText.split(';')) {
          if (!decl.includes('var(--')) continue;
          const prop = decl.split(':')[0].trim();
          for (const m of decl.matchAll(/var\(\s*(--[\w-]+)\s*(,)?/g)) {
            const [, name, hasFallback] = m;
            if (resolves(name)) continue;
            const entry = { selector: rule.selectorText, property: prop, token: name };
            // Two different bugs, never merged. No fallback = the declaration
            // is INVALID and dropped entirely. With fallback = it silently
            // renders the fallback forever. The first is the fatal one.
            (hasFallback ? l1.unresolvedWithFallback : l1.unresolvedNoFallback).push(entry);
          }
        }
      }
    };
    for (const sheet of document.styleSheets) {
      try { walk(sheet.cssRules); l1.sheetsScanned++; }
      catch (e) { l1.sheetsBlocked++; }   // cross-origin sheets throw; counted, not ignored
    }

    // ── L2: the touched selectors, from the diff ────────────────────────────
    // L2a -- does the deployed rule for this selector resolve? Complete over
    //        all of them, element or no element.
    // L2b -- where an element actually renders, is the change observable?
    const norm = (s) => s.replace(/\s*,\s*/g, ',').replace(/\s+/g, ' ').trim();
    const byRule = new Map();
    const collect = (rules) => {
      for (const rule of rules) {
        if (rule.cssRules && rule.cssRules.length) collect(rule.cssRules);
        // Chromium re-serialises selector lists with a space after each comma
        // (`a,b` -> `a, b`), so the diff-derived key would miss them. Normalise
        // both sides by stripping whitespace around commas.
        if (rule.selectorText) byRule.set(norm(rule.selectorText), rule);
      }
    };
    for (const sheet of document.styleSheets) {
      try { collect(sheet.cssRules); } catch (e) {}
    }

    const rows = touched.selectors.map(({ selector, properties }) => {
      const rule = byRule.get(norm(selector));
      const unresolved = [];
      if (rule) {
        // cssText for the same shorthand reason as L1.
        for (const decl of rule.style.cssText.split(';')) {
          if (!decl.includes('var(--')) continue;
          const prop = decl.split(':')[0].trim();
          for (const m of decl.matchAll(/var\(\s*(--[\w-]+)/g)) {
            if (!resolves(m[1])) unresolved.push({ property: prop, token: m[1] });
          }
        }
      }
      let el = null;
      try { el = document.querySelector(selector); } catch (e) {}
      let observable = null, computed = null, parentComputed = null;
      if (el && el.parentElement && properties.includes('color')) {
        computed = getComputedStyle(el).color;
        parentComputed = getComputedStyle(el.parentElement).color;
        // The whole point of REFRAME 2. Equal means the pre-fix inherited
        // value was already this colour, so the fix changed nothing visible.
        observable = computed !== parentComputed;
      }
      return {
        selector, properties,
        ruleFound: !!rule,
        unresolved,
        // A -moz- prefixed rule is dropped by Chromium's parser outright. That
        // is not a failure of the fix, it is a rule this engine never had.
        // Given its own verdict so it neither fails the run nor counts as
        // verified -- Chromium cannot speak to it either way.
        l2aVerdict: !rule
          ? (/-moz-|::-moz/.test(selector) ? 'NOT-IN-THIS-ENGINE' : 'RULE-NOT-FOUND')
          : unresolved.length ? 'FAIL' : 'PASS',
        elementPresent: !!el,
        computed, parentComputed, observable,
      };
    });

    return { l1, rows, bodyColor: getComputedStyle(document.body).color };
  }, TOUCHED);

  const { l1, rows, bodyColor } = result;
  const l1RegressionList = l1.unresolvedNoFallback.filter((e) => !STOP_LISTED.includes(e.token));
  const l2aPass = rows.filter((r) => r.l2aVerdict === 'PASS').length;
  const l2aFail = rows.filter((r) => r.l2aVerdict === 'FAIL').length;
  const notFound = rows.filter((r) => r.l2aVerdict === 'RULE-NOT-FOUND').length;
  const notInEngine = rows.filter((r) => r.l2aVerdict === 'NOT-IN-THIS-ENGINE').length;
  const rendered = rows.filter((r) => r.observable !== null);
  const visible = rendered.filter((r) => r.observable);
  const invisible = rendered.filter((r) => !r.observable);

  const manifest = {
    ts: TS, url: URL, viewport: VIEWPORT,
    ccCmd: 'CC-CMD-2026-08-09-token-resolution-audit',
    swVersion: await page.evaluate(() => window.SW_VERSION || null),
    bodyColor,
    sourceCommits: TOUCHED.commits,
    // Bounds the coverage claim: these changed sites have no selector and are
    // NOT covered by L2. Stated so the audit cannot read as total.
    jsInlineStyleSitesNotCovered: TOUCHED.jsInlineStyleSites.length,
    l1: {
      ...l1,
      stopListed: STOP_LISTED,
      // THE headline assertion: zero unresolvable references EXCEPT the
      // documented decisions. Anything else is a live rendering defect.
      knownStopListed: l1.unresolvedNoFallback.filter((e) => STOP_LISTED.includes(e.token)).length,
      regressions: l1RegressionList,
      verdict: l1RegressionList.length === 0 ? 'PASS' : 'FAIL',
    },
    l2: {
      total: rows.length, pass: l2aPass, fail: l2aFail, ruleNotFound: notFound,
      notInThisEngine: notInEngine,
      rendered: rendered.length,
      observableChanges: visible.length,
      provablyInvisibleChanges: invisible.length,
      verdict: l2aFail === 0 && notFound === 0 ? 'PASS' : 'FAIL',
    },
    conclusive: l1RegressionList.length === 0 && l2aFail === 0 && notFound === 0,
    l1UnresolvedNoFallback: l1.unresolvedNoFallback,
    l1UnresolvedWithFallback: l1.unresolvedWithFallback,
    rows,
  };

  const base = `outbox/token-resolution-probe-${TS}`;
  fs.writeFileSync(`${base}-manifest.json`, JSON.stringify(manifest, null, 2));
  // Image only the selectors whose change is actually observable -- the small
  // set where a picture carries information.
  for (const r of visible.slice(0, 12)) {
    const safe = r.selector.replace(/[^a-z0-9]+/gi, '_').slice(0, 40);
    await page.locator(r.selector).first().screenshot({ path: `${base}-${safe}.png` }).catch(() => {});
  }
  await browser.close();

  console.log(`L1 ${manifest.l1.verdict}: ${l1.rulesScanned} rules / ${l1.sheetsScanned} sheets (${l1.sheetsBlocked} blocked)`);
  console.log(`   unresolved NO-fallback: ${l1.unresolvedNoFallback.length} (stop-listed ${manifest.l1.knownStopListed}, REGRESSIONS ${l1RegressionList.length})`);
  console.log(`   unresolved WITH fallback (silent): ${l1.unresolvedWithFallback.length}`);
  console.log(`L2 ${manifest.l2.verdict}: ${l2aPass}/${rows.length} rules resolve, ruleNotFound=${notFound}`);
  console.log(`   rendered=${rendered.length}  observable=${visible.length}  provably-invisible=${invisible.length}`);
  console.log(`conclusive=${manifest.conclusive}`);
  process.exit(manifest.conclusive ? 0 : 1);
})().catch((e) => { console.error('probe failed:', e.stack || e.message); process.exit(1); });
