// CC-CMD-2026-08-09-token-resolution-audit, extended by
// CC-CMD-2026-08-09-observability-coverage.
//
// REFRAME 1 -- verify the universal, not the instances.
//   A phantom token is structurally detectable at runtime: a var(--x) whose
//   --x resolves to empty on :root. So instead of asking "are these 74 right",
//   sweep the ENTIRE deployed CSSOM and prove ZERO unresolvable references
//   remain anywhere. Proof of absence beats 74 proofs of presence, and it
//   covers rules never listed and never touched.
//
// REFRAME 2 -- was each change observable at all?
//   The failure mode was: declaration invalid -> dropped -> the property falls
//   back to what it would have been without the rule. Crucially that fallback
//   DIFFERS BY PROPERTY, and the first version of this probe got it wrong by
//   applying the inherited-property rule to everything and then only ever
//   evaluating `color`:
//
//     inherited  (color, font-family)  pre-fix = the PARENT's computed value
//                                      -> observable iff computed != parent's
//     non-inherited (background,       pre-fix = the property's INITIAL value
//        border-*)                        (transparent / none)
//                                      -> observable iff computed != initial,
//                                         which needs no ancestor chain and so
//                                         is decidable even when nothing renders
//
//   That distinction is not a detail. 24 of the touched property-instances are
//   non-inherited, and treating them as inherited would have compared a
//   background against a parent's background for no reason.
//
// COVERAGE -- the previous run evaluated observability on 2 of 74 selectors,
//   because the other 72 do not render at page load. This version opens the
//   app's own views through the functions it exposes on window and re-measures
//   in each state. It does NOT synthesise elements: the inherited-property
//   question is literally "what does this inherit", and a detached node has no
//   ancestor chain, so a synthetic stand-in would answer confidently and
//   wrongly.
//
// Target selectors come from outbox/touched-selectors.json, generated by
// scripts/derive-touched-selectors.mjs from the fix commits themselves. Never
// hand-listed: a remembered list only checks what the author recalled, and the
// forgotten selector is the one that breaks.

const { chromium } = require('@playwright/test');
const fs = require('fs');

const URL = process.env.FIELD_URL || 'https://jubilant-bassoon.jeffunglesbee.workers.dev';
const TS = new Date().toISOString().replace(/[:.]/g, '-');
const VIEWPORT = { width: 1440, height: 900 };

const TOUCHED = JSON.parse(fs.readFileSync('outbox/touched-selectors.json', 'utf8'));

// The tokens CC-CMD-2026-08-09-phantom-css-token-audit DELIBERATELY left
// unresolved, each with a stated reason in its outbox doc: Rule 37 reserves no
// meaning for green/orange/"accent", and red is "elimination urgency ONLY" so
// .vibe.blood cannot take it.
//
// Encoding them is what makes L1 a usable gate rather than a permanent red
// light. Without it `conclusive` could never be true and the artifact would be
// ignored within a week. With it, any NEW unresolvable token fails loudly.
const STOP_LISTED = ['--green', '--red', '--orange', '--accent'];

// Views reachable through the app's own API. window.* only — the app ships as
// an ES module, so nothing is global except what it explicitly assigns.
// Signatures were read from source, not guessed: toggleThreadDrawer takes a
// gameId and returns early if no matching card exists, and setViewerIntelMode
// only accepts 'stories' | 'myteams' | 'stakes'. Calling either with the wrong
// argument would silently mount nothing and be indistinguishable from "this
// view has no touched selectors" -- a false NOT-RENDERED.
const STATES = [
  { key: 'load', fn: null },
  { key: 'journalism', fn: 'toggleJournalismView' },
  { key: 'wc-groups', fn: 'toggleWCView', then: ['switchWCTab', 'groups'] },
  { key: 'wc-bracket', fn: null, then: ['switchWCTab', 'bracket'] },
  { key: 'wc-off', fn: 'toggleWCView' },
  { key: 'pickem', fn: 'togglePickEmView' },
  { key: 'pickem-off', fn: 'togglePickEmView' },
  { key: 'stats', fn: 'toggleStatsView' },
  { key: 'stats-off', fn: 'toggleStatsView' },
  { key: 'viewer-intel-stories', fn: 'setViewerIntelMode', arg: 'stories' },
  { key: 'viewer-intel-stakes', fn: 'setViewerIntelMode', arg: 'stakes' },
  // toggleThreadDrawer needs a real card id, taken from the DOM at call time.
  { key: 'thread', fnRaw: `const c=document.querySelector('.game-card[data-gameid]');
      if(!c) throw new Error('no .game-card[data-gameid] on the page');
      window.toggleThreadDrawer(c.getAttribute('data-gameid'));` },
];

(async () => {
  const browser = await chromium.launch(
    process.env.PW_EXECUTABLE ? { executablePath: process.env.PW_EXECUTABLE } : {});
  const page = await browser.newPage({ viewport: VIEWPORT });
  await page.goto(URL, { waitUntil: 'domcontentloaded', timeout: 20000 });
  await page.waitForSelector('.game-card', { timeout: 25000 }).catch(() => {});

  // ── L1 + L2a: measured once; neither depends on which view is open ────────
  const base = await page.evaluate((touched) => {
    const rootCS = getComputedStyle(document.documentElement);
    const resolves = (name) => rootCS.getPropertyValue(name).trim() !== '';

    const l1 = { rulesScanned: 0, sheetsScanned: 0, sheetsBlocked: 0,
                 unresolvedNoFallback: [], unresolvedWithFallback: [] };
    // `if (rule.cssRules) ... continue` would be WRONG, and was: modern
    // Chromium gives every CSSStyleRule an empty .cssRules because CSS nesting
    // is supported, so that branch recursed into nothing and skipped all 1539
    // style rules -- the probe reported PASS having scanned 51 of 1891.
    const walk = (rules) => {
      for (const rule of rules) {
        if (rule.cssRules && rule.cssRules.length) walk(rule.cssRules);
        if (!rule.style) continue;
        l1.rulesScanned++;
        // style.cssText, NOT an index walk over rule.style: that enumerates
        // LONGHANDS, and a shorthand carrying an unresolvable var()
        // (`border-color:var(--red)`) cannot be expanded at parse time, so it
        // is invisible to the index walk. Cost me 3 of 11 findings.
        for (const decl of rule.style.cssText.split(';')) {
          if (!decl.includes('var(--')) continue;
          const prop = decl.split(':')[0].trim();
          for (const m of decl.matchAll(/var\(\s*(--[\w-]+)\s*(,)?/g)) {
            const [, name, hasFallback] = m;
            if (resolves(name)) continue;
            const entry = { selector: rule.selectorText, property: prop, token: name };
            // Two different bugs, never merged. No fallback = the declaration
            // is INVALID and dropped. With fallback = renders the fallback
            // forever. The first is the fatal one.
            (hasFallback ? l1.unresolvedWithFallback : l1.unresolvedNoFallback).push(entry);
          }
        }
      }
    };
    for (const sheet of document.styleSheets) {
      try { walk(sheet.cssRules); l1.sheetsScanned++; }
      catch (e) { l1.sheetsBlocked++; }   // cross-origin sheets throw; counted, not ignored
    }

    const norm = (s) => s.replace(/\s*,\s*/g, ',').replace(/\s+/g, ' ').trim();
    const byRule = new Map();
    const collect = (rules) => {
      for (const rule of rules) {
        if (rule.cssRules && rule.cssRules.length) collect(rule.cssRules);
        // Chromium re-serialises selector lists as `a, b`, so the diff-derived
        // key would miss them without normalising both sides.
        if (rule.selectorText) byRule.set(norm(rule.selectorText), rule);
      }
    };
    for (const sheet of document.styleSheets) {
      try { collect(sheet.cssRules); } catch (e) {}
    }

    // Inheritance is a property of the CSS property, not something to guess.
    // Asked of the engine rather than hardcoded from memory where possible;
    // the list is small and exact for the properties this audit touched.
    const INHERITED = new Set(['color', 'font-family', 'font-size', 'font-weight',
                               'letter-spacing', 'line-height', 'text-align', 'visibility']);

    const rows = touched.selectors.map(({ selector, properties }) => {
      const rule = byRule.get(norm(selector));
      const unresolved = [];
      if (rule) {
        for (const decl of rule.style.cssText.split(';')) {
          if (!decl.includes('var(--')) continue;
          const prop = decl.split(':')[0].trim();
          for (const m of decl.matchAll(/var\(\s*(--[\w-]+)/g)) {
            if (!resolves(m[1])) unresolved.push({ property: prop, token: m[1] });
          }
        }
      }
      // Non-inherited properties are decidable with NO element: pre-fix the
      // declaration was dropped, so the property took its initial value
      // (transparent for background/border-color). Post-fix it takes a token
      // that resolves to an opaque colour. Different by construction.
      const nonInherited = properties.filter((p) => !INHERITED.has(p));
      const staticallyObservable = rule && nonInherited.length > 0
        ? nonInherited.some((p) => {
            const v = rule.style.getPropertyValue(p) || rule.style.cssText;
            const m = v.match(/var\(\s*(--[\w-]+)/);
            if (!m) return false;
            const tv = rootCS.getPropertyValue(m[1]).trim();
            return tv !== '' && tv !== 'transparent';
          })
        : null;

      return {
        selector, properties,
        inheritedProps: properties.filter((p) => INHERITED.has(p)),
        nonInheritedProps: nonInherited,
        ruleFound: !!rule,
        unresolved,
        // A -moz- rule is dropped by Chromium's parser outright. Not a failure
        // of the fix -- a rule this engine never had. Its own verdict so it
        // neither fails the run nor counts as verified.
        l2aVerdict: !rule
          ? (/-moz-|::-moz/.test(selector) ? 'NOT-IN-THIS-ENGINE' : 'RULE-NOT-FOUND')
          : unresolved.length ? 'FAIL' : 'PASS',
        staticallyObservable,
      };
    });

    return { l1, rows, bodyColor: getComputedStyle(document.body).color };
  }, TOUCHED);

  // ── L2b: measure inherited-property observability across app states ───────
  const measured = new Map();          // selector -> measurement
  const stateLog = [];
  for (const st of STATES) {
    let err = null;
    if (st.fn || st.then || st.fnRaw) {
      err = await page.evaluate(({ fn, arg, then, fnRaw }) => {
        try {
          if (fnRaw) { new Function(fnRaw)(); return null; }
          if (fn) arg === undefined ? window[fn]() : window[fn](arg);
          if (then) window[then[0]](then[1]);
          return null;
        } catch (e) { return String(e && e.message || e).slice(0, 160); }
      }, { fn: st.fn, arg: st.arg, then: st.then, fnRaw: st.fnRaw });
      await page.waitForTimeout(600);
    }
    const found = await page.evaluate((sels) => {
      const out = {};
      for (const { selector, inheritedProps } of sels) {
        if (!inheritedProps.length) continue;
        let el = null;
        try { el = document.querySelector(selector); } catch (e) { continue; }
        if (!el || !el.parentElement) continue;
        const cs = getComputedStyle(el), ps = getComputedStyle(el.parentElement);
        // One entry per inherited property: `color` and `font-family` can
        // disagree about observability on the same element.
        out[selector] = inheritedProps.map((p) => ({
          property: p,
          computed: cs.getPropertyValue(p),
          parentComputed: ps.getPropertyValue(p),
          observable: cs.getPropertyValue(p) !== ps.getPropertyValue(p),
        }));
      }
      return out;
    }, base.rows.map((r) => ({ selector: r.selector, inheritedProps: r.inheritedProps })));

    let newlyMeasured = 0;
    for (const [sel, vals] of Object.entries(found)) {
      if (measured.has(sel)) continue;      // first state that renders it wins
      measured.set(sel, { state: st.key, values: vals });
      newlyMeasured++;
    }
    stateLog.push({ state: st.key, error: err, selectorsRenderedHere: Object.keys(found).length, newlyMeasured });
  }

  const rows = base.rows.map((r) => {
    const m = measured.get(r.selector);
    return {
      ...r,
      measuredInState: m ? m.state : null,
      inheritedMeasurements: m ? m.values : null,
      // Merged view: a selector is observable if ANY of its properties is --
      // by measurement for inherited ones, statically for the rest.
      observable: m ? m.values.some((v) => v.observable)
                    : (r.staticallyObservable === true ? true : null),
      observabilityBasis: m ? 'measured' : (r.staticallyObservable !== null ? 'static' : null),
    };
  });

  const { l1 } = base;
  const l1Regressions = l1.unresolvedNoFallback.filter((e) => !STOP_LISTED.includes(e.token));
  const l2aPass = rows.filter((r) => r.l2aVerdict === 'PASS').length;
  const l2aFail = rows.filter((r) => r.l2aVerdict === 'FAIL').length;
  const notFound = rows.filter((r) => r.l2aVerdict === 'RULE-NOT-FOUND').length;
  const notInEngine = rows.filter((r) => r.l2aVerdict === 'NOT-IN-THIS-ENGINE').length;
  const decided = rows.filter((r) => r.observable !== null);
  const visible = decided.filter((r) => r.observable);
  const invisible = decided.filter((r) => !r.observable);

  const manifest = {
    ts: TS, url: URL, viewport: VIEWPORT,
    ccCmd: 'CC-CMD-2026-08-09-observability-coverage',
    swVersion: await page.evaluate(() => window.SW_VERSION || null),
    bodyColor: base.bodyColor,
    sourceCommits: TOUCHED.commits,
    jsInlineStyleSitesNotCovered: TOUCHED.jsInlineStyleSites.length,
    stateLog,
    l1: {
      ...l1, stopListed: STOP_LISTED,
      knownStopListed: l1.unresolvedNoFallback.filter((e) => STOP_LISTED.includes(e.token)).length,
      regressions: l1Regressions,
      verdict: l1Regressions.length === 0 ? 'PASS' : 'FAIL',
    },
    l2: {
      total: rows.length, pass: l2aPass, fail: l2aFail,
      ruleNotFound: notFound, notInThisEngine: notInEngine,
      measuredByRender: measured.size,
      decidedStatically: rows.filter((r) => r.observabilityBasis === 'static').length,
      undecided: rows.length - decided.length,
      observableChanges: visible.length,
      provablyInvisibleChanges: invisible.length,
      verdict: l2aFail === 0 && notFound === 0 ? 'PASS' : 'FAIL',
    },
    conclusive: l1Regressions.length === 0 && l2aFail === 0 && notFound === 0,
    l1UnresolvedNoFallback: l1.unresolvedNoFallback,
    l1UnresolvedWithFallback: l1.unresolvedWithFallback,
    rows,
  };

  const out = `outbox/token-resolution-probe-${TS}`;
  fs.writeFileSync(`${out}-manifest.json`, JSON.stringify(manifest, null, 2));
  for (const r of visible.filter((x) => x.observabilityBasis === 'measured').slice(0, 15)) {
    const safe = r.selector.replace(/[^a-z0-9]+/gi, '_').slice(0, 40);
    await page.locator(r.selector).first().screenshot({ path: `${out}-${safe}.png` }).catch(() => {});
  }
  await browser.close();

  console.log(`L1 ${manifest.l1.verdict}: ${l1.rulesScanned} rules, regressions ${l1Regressions.length}, stop-listed ${manifest.l1.knownStopListed}`);
  console.log(`L2 ${manifest.l2.verdict}: ${l2aPass}/${rows.length} resolve, notFound ${notFound}, notInEngine ${notInEngine}`);
  console.log(`   observability: measured ${measured.size}, static ${manifest.l2.decidedStatically}, undecided ${manifest.l2.undecided}`);
  console.log(`   observable ${visible.length}, provably-invisible ${invisible.length}`);
  for (const s of stateLog) console.log(`   state ${s.state.padEnd(11)} rendered ${String(s.selectorsRenderedHere).padStart(3)}  new ${String(s.newlyMeasured).padStart(3)}  err=${s.error}`);
  console.log(`conclusive=${manifest.conclusive}`);
  process.exit(manifest.conclusive ? 0 : 1);
})().catch((e) => { console.error('probe failed:', e.stack || e.message); process.exit(1); });
